# Uptime Kuma Service Module
# This module creates a Hetzner VM for Uptime Kuma monitoring service using WebKit's server module

terraform {
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = "~> 1.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

provider "hcloud" {
  token = var.hetzner_token
}

# Use WebKit's Hetzner server module
# This creates the VM, SSH keys, firewall, and installs Ansible via cloud-init
module "server" {
  source = "github.com/ainsleydev/webkit//platform/terraform/providers/hetzner/server?ref=main"

  name        = var.service_name
  server_type = var.server_type
  location    = var.location
  tags        = var.tags
}

# Generate Ansible inventory file automatically
resource "local_file" "ansible_inventory" {
  filename = "${path.root}/../../ansible/inventory-uptime-kuma.ini"
  content  = <<-EOT
    # Auto-generated by Terraform - DO NOT EDIT MANUALLY
    # Last updated: ${timestamp()}

    [uptime_kuma]
    ${var.domain} ansible_host=${module.server.ip_address} ansible_user=${module.server.server_user}

    [uptime_kuma:vars]
    domain=${var.domain}
    admin_email=${var.admin_email}
  EOT

  file_permission = "0644"
}
