output "server_id" {
  description = "Hetzner server ID"
  value       = module.server.id
}

output "server_ip" {
  description = "Public IPv4 address of the Uptime Kuma server"
  value       = module.server.ip_address
}

output "ssh_private_key" {
  description = "SSH private key for server access (generated by Terraform)"
  value       = module.server.ssh_private_key
  sensitive   = true
}

output "ssh_public_key" {
  description = "SSH public key"
  value       = module.server.ssh_public_key
}

output "ssh_user" {
  description = "SSH username for server access"
  value       = module.server.server_user
}

output "volume_id" {
  description = "Hetzner volume ID"
  value       = module.volume.id
}

output "volume_device" {
  description = "Volume device path on the server"
  value       = module.volume.linux_device
}

output "domain" {
  description = "Domain for Uptime Kuma instance"
  value       = var.domain
}

output "ansible_inventory_path" {
  description = "Path to the auto-generated Ansible inventory file"
  value       = local_file.ansible_inventory.filename
}

output "access_instructions" {
  description = "Instructions for accessing the server"
  value       = <<-EOT
    Uptime Kuma Server Details:
    ---------------------------
    IP Address: ${module.server.ip_address}
    Domain: ${var.domain}
    SSH User: ${module.server.server_user}

    Ansible inventory file generated at: ${local_file.ansible_inventory.filename}

    To SSH into the server:
    1. Save the SSH private key: make ssh-key
    2. Connect: ssh -i uptime-kuma-key.pem ${module.server.server_user}@${module.server.ip_address}

    DNS Configuration Required:
    ---------------------------
    Add an A record for ${var.domain} pointing to ${module.server.ip_address}

    To deploy or update Uptime Kuma with Ansible:
    make deploy-uptime

    Then access at: https://${var.domain}
  EOT
}
