output "server_id" {
  description = "Hetzner server ID"
  value       = hcloud_server.this.id
}

output "server_ip" {
  description = "Public IPv4 address of the Uptime Kuma server"
  value       = hcloud_server.this.ipv4_address
}

output "ssh_private_key" {
  description = "SSH private key for server access (generated by Terraform)"
  value       = tls_private_key.this.private_key_pem
  sensitive   = true
}

output "ssh_public_key" {
  description = "SSH public key"
  value       = tls_private_key.this.public_key_openssh
}

output "ssh_user" {
  description = "SSH username for server access"
  value       = "root"
}

output "volume_id" {
  description = "Hetzner volume ID"
  value       = hcloud_volume.uptime_kuma_data.id
}

output "volume_device" {
  description = "Volume device path on the server"
  value       = "/dev/disk/by-id/scsi-0HC_Volume_${hcloud_volume.uptime_kuma_data.id}"
}

output "domain" {
  description = "Domain for Uptime Kuma instance"
  value       = var.domain
}

output "access_instructions" {
  description = "Instructions for accessing the server"
  value       = <<-EOT
    Uptime Kuma Server Details:
    ---------------------------
    IP Address: ${hcloud_server.this.ipv4_address}
    Domain: ${var.domain}
    SSH User: root

    To SSH into the server:
    1. Save the SSH private key: terraform output -raw ssh_private_key > uptime-kuma-key.pem
    2. Set permissions: chmod 600 uptime-kuma-key.pem
    3. Connect: ssh -i uptime-kuma-key.pem root@${hcloud_server.this.ipv4_address}

    DNS Configuration Required:
    ---------------------------
    Add an A record for ${var.domain} pointing to ${hcloud_server.this.ipv4_address}

    After DNS is configured, the service will be available at:
    https://${var.domain}

    Monitoring cloud-init progress:
    -------------------------------
    tail -f /var/log/cloud-init-output.log
  EOT
}
